# Generated by Django 3.0 on 2021-04-16 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupo_cid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CID',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grupo_cid.GrupoCID')),
            ],
            options={
                'verbose_name': 'CID',
                'verbose_name_plural': 'CIDs',
                'db_table': 'tab_cid',
            },
        ),
    ]
