# Generated by Django 3.0 on 2021-04-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoCID',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Grupo CID',
                'verbose_name_plural': 'Grupos CID',
                'db_table': 'tab_grupo_cid',
            },
        ),
    ]
